version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - .:/app
    build: .
    ports:
      - 8000:8000

  mongo:
    image: mongo
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
