version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - .:/app
    build: .
    ports:
      - 8000:8000

  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
