# Generated by Django 4.1.3 on 2022-11-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name')),
                ('color', models.CharField(max_length=255, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='username')),
                ('fullname', models.CharField(max_length=255, verbose_name='fullname')),
                ('image_url', models.CharField(max_length=255, verbose_name='image_url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('following', models.ManyToManyField(blank=True, to='api.user')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='api.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('tweet_text', models.CharField(max_length=255, verbose_name='tweet_text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.user')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to='api.user')),
                ('reply', models.ManyToManyField(blank=True, to='api.tweet')),
                ('retweet', models.ManyToManyField(blank=True, related_name='retweet', to='api.user')),
            ],
        ),
    ]
